services:
  php:
    build:
      context: ./docker/php
    working_dir: /app
    volumes:
      - ".:/app"
    user: "${UID:-1000}:${GID:-1000}"

  postgres:
    image: postgres:13
    volumes:
      - "./docker/pgsql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: vendee
      POSTGRES_PASSWORD: globe
    command: ["postgres", "-c", "log_statement=all"]
